# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import orangeCrypt 

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 600)
                MainWindow.setStyleSheet("\n"
        "color: rgb(255, 170, 127);\n"
        "background-color: rgb(46, 46, 46);")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(210, 50, 161, 81))
                self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: rgb(255, 138, 52);\n"
        "font: 20pt \"MS Shell Dlg 2\";")
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(50, 50, 161, 81))
                self.label.setMouseTracking(False)
                self.label.setAutoFillBackground(False)
                self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 138, 52);\n"
        "border: 2px solid rgb(255, 138, 52);;\n"
        "padding: 10px;")
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(140, 230, 100, 50))
                self.label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 138, 52);")
                self.label_3.setObjectName("label_3")
                self.encword = QtWidgets.QPlainTextEdit(self.centralwidget)
                self.encword.setGeometry(QtCore.QRect(250, 230, 350, 50))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 138, 52))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
                self.encword.setPalette(palette)
                self.encword.setFocusPolicy(QtCore.Qt.StrongFocus)
                self.encword.setStyleSheet("color:  rgb(255, 138, 52);\n"
        "font: 11pt \"MS Shell Dlg 2\";")
                self.encword.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.encword.setBackgroundVisible(False)
                self.encword.setObjectName("encword")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(140, 340, 100, 50))
                self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 138, 52);")
                self.label_5.setObjectName("label_5")
                self.decword = QtWidgets.QPlainTextEdit(self.centralwidget)
                self.decword.setGeometry(QtCore.QRect(250, 340, 350, 50))
                self.decword.setStyleSheet("color:  rgb(255, 138, 52);\n"
        "font: 11pt \"MS Shell Dlg 2\";")
                self.decword.setObjectName("decword")
                self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
                self.spinBox.setGeometry(QtCore.QRect(660, 270, 91, 91))
                self.spinBox.setStyleSheet("color:  rgb(255, 138, 52);\n"
        "font: 11pt \"MS Shell Dlg 2\";")
                self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
                self.spinBox.setMaximum(9)
                self.spinBox.setObjectName("spinBox")
                self.encButton = QtWidgets.QPushButton(self.centralwidget)
                self.encButton.setGeometry(QtCore.QRect(170, 450, 200, 80))
                self.encButton.setStyleSheet("border:2px solid rgb(255, 138, 52);\n"
        "color: rgb(255, 138, 52);")
                self.encButton.setObjectName("encButton")
                self.decButton = QtWidgets.QPushButton(self.centralwidget)
                self.decButton.setGeometry(QtCore.QRect(410, 450, 200, 80))
                self.decButton.setStyleSheet("border:2px solid  rgb(255, 138, 52);\n"
        "color: rgb(255, 138, 52);")
                self.decButton.setObjectName("decButton")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(660, 210, 81, 51))
                self.label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 138, 52);")
                self.label_4.setAlignment(QtCore.Qt.AlignCenter)
                self.label_4.setObjectName("label_4")
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_2.setText(_translate("MainWindow", "CRYPT"))
                self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
                self.label.setText(_translate("MainWindow", "Orange"))
                self.label_3.setText(_translate("MainWindow", "Encrypt Word:"))
                self.label_5.setText(_translate("MainWindow", "Decrypt Word:"))
                self.encButton.setText(_translate("MainWindow", "ENCRYPT"))
                self.decButton.setText(_translate("MainWindow", "DECRYPT"))
                self.label_4.setText(_translate("MainWindow", "Key:"))
                
                self.encButton.clicked.connect(self.do_enc)
                self.decButton.clicked.connect(self.do_dec)
        
        encrpt_word = ""
        decrpt_word = ""
        
        def do_enc(self):
                self.encrpt_word = orangeCrypt.ENCRYPT(self.encword.toPlainText(), self.spinBox.value())
                self.decword.setPlainText(self.encrpt_word)
        def do_dec(self):
                self.decrpt_word = orangeCrypt.DECRYPT(self.decword.toPlainText(), self.spinBox.value())
                self.encword.setPlainText(self.decrpt_word)
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
